# Generated by Django 5.1.2 on 2024-11-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='valor_alvo',
            new_name='valor_meta',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='usuario',
        ),
    ]
