# Generated by Django 5.1.2 on 2024-11-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_rename_valor_alvo_meta_valor_meta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='categoria',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
    ]
