# Generated by Django 5.1.2 on 2024-11-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_alter_categoria_icone_alter_meta_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Limit',
            new_name='Limites',
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(default='#FFFFFF', max_length=7)),
                ('orcamento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icone', models.CharField(default='default_icon', max_length=50)),
                ('padrao', models.BooleanField(default=False)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financas.subcategoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
    ]
