# Generated by Django 5.1.2 on 2024-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_rename_limit_limites_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cartao', models.CharField(choices=[('MASTER', 'Mastercard'), ('INTER', 'Inter')], max_length=10)),
                ('nome_cartao', models.CharField(max_length=100)),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
