# Generated by Django 5.1.2 on 2024-11-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0012_logo_transacao_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='descricao',
        ),
    ]
