# Generated by Django 5.1.2 on 2024-11-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financas', '0013_rename_nome_transacao_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
