# Generated by Django 5.1.2 on 2024-11-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0015_remove_banco_icone_banco_codigo_banco_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='cor_principal',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
