# Generated by Django 5.1.2 on 2024-11-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0016_banco_cor_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banco',
            old_name='cor_principal',
            new_name='cor',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default='icons/categorias/default.svg', max_length=200),
        ),
    ]
