# Generated by Django 5.1.2 on 2024-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0017_rename_cor_principal_banco_cor_alter_categoria_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(blank=True, default='icons/categorias/default.svg', null=True, upload_to='icons/categorias/'),
        ),
    ]
