# Generated by Django 5.1.2 on 2024-11-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0018_alter_categoria_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default='icons/categorias/default.svg', max_length=255),
        ),
    ]
