# Generated by Django 5.1.2 on 2024-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0020_remove_cartao_tipo_cartao_cartao_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='data_fechamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='data_vencimento',
            field=models.IntegerField(),
        ),
    ]
