# Generated by Django 5.1.2 on 2024-11-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0021_alter_cartao_data_fechamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='usuario',
        ),
    ]
