# Generated by Django 5.1.2 on 2024-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0023_remove_pagamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('vence_hoje', 'Vence Hoje')], default='pendente', max_length=15),
        ),
    ]
