# Generated by Django 5.1.2 on 2024-11-22 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0024_pagamento_categoria_pagamento_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
